### PR TITLE
VULN-3042 [g11n-langneg] minimist has vulnerabilities

### PR DESCRIPTION
**Pull request by mtomescu**
Upgraded minimist module to 1.2.6

### CODE REVIEW

**Review by piroscacostin — APPROVED** [review]

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

## 1.2.10 (https://github.com/Tradeshift/g11n-langneg/compare/v1.2.9...v1.2.10) (2022-05-05)

### Bug Fixes

 - deps: minimist (bed219d (https://github.com/Tradeshift/g11n-langneg/commit/bed219dc29ef10c943ae8bc7efd017e14ddffbd2))

**Comment by mtomescu** [comment]
Closing this PR as it was duplicated by:
https://github.com/Tradeshift/g11n-langneg/pull/36

**Pull request closed without merging**
